version: "3"
volumes: 
  node_modules:
services:
  app:
    build:
      context: ./
    container_name: aistudent-frontend
    ports:
      - "12012:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm run dev"