version: "3"
volumes: 
  node_modules:
services:
  app:
    build:
      context: ./
    container_name: aistudent-frontend
    ports:
      - "12012:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm run dev"
    depends_on:
     - db
  db:
    image: mysql:8.0
    container_name: aistudent-db
    ports:
      - 3307:3307
    volumes:
      - ./data:/docker-entrypoint-initdb.d/
      - ./mysql/my.conf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYQL_DATABASE=test