version: "3"
volumes: 
  node_modules:
services:
  app:
    build:
      context: ./
    container_name: aistudent-frontend
    ports:
      - "12012:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
      - NEXTAUTH_URL=$NEXTAUTH_URL
      - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
    command: sh -c "npm run dev"
